Repository DIT113-V22/group-05, pull requests merged in 2022-05, with the labels that each got.

#54 Incoming avoidance
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  arduino/smartcar/smartcar.ino
Labels: Sprint #2

#55 Add Joystick
  android/app/src/main/java/platis/solutions/smartcarmqttcontroller/JoystickView.java
  android/app/src/main/java/platis/solutions/smartcarmqttcontroller/MainActivity.java
  android/app/src/main/res/layout/activity_main.xml
  arduino/smartcar/smartcar.ino
Labels: Sprint #3

#57 Debug
  android/app/src/main/java/platis/solutions/smartcarmqttcontroller/JoystickView.java
  android/app/src/main/java/platis/solutions/smartcarmqttcontroller/MainActivity.java
  arduino/smartcar/smartcar.ino
Labels: Sprint #3

#64 Change infrared sensors to UltraSonic sensors
  android/app/src/main/java/safetyfirst/androidapp/safetyfirstcontroller/MainActivity.java
  arduino/smartcar/board_config.json
  arduino/smartcar/smartcar.ino
  arduino/smartcar/vehicle_config.json
Labels: Sprint #3, improvement

#70 Bug fixes relating to joystick and toggle button
  android/app/src/main/java/safetyfirst/androidapp/safetyfirstcontroller/JoystickView.java
  android/app/src/main/java/safetyfirst/androidapp/safetyfirstcontroller/MainActivity.java
  arduino/smartcar/smartcar.ino
Labels: Sketch, App, improvement

#76 Implement code logic for registering a collision
  arduino/smartcar/smartcar.ino
  arduino/smartcar/vehicle_config.json
Labels: Sprint #3, Sprint #4

#78 Limiting the car reverse speed
  android/app/src/main/java/safetyfirst/androidapp/safetyfirstcontroller/MainActivity.java
Labels: Sprint #4

#84 Add functionality that register crash and activates pop-up
  android/app/src/main/java/safetyfirst/androidapp/safetyfirstcontroller/MainActivity.java
  android/app/src/main/res/menu/first_menu.xml
  android/build.gradle
  arduino/smartcar/smartcar.ino
Labels: Bug, Sprint #4

#83 Make final design iteration.
  android/app/src/main/res/drawable/connected.png
  android/app/src/main/res/drawable/no_connection.png
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/crash_popup.xml
Labels: Sprint #4

#86 Add MIT License to project
  LICENSE
Labels: Documentation

#87 Update README.md
  README.md
Labels: Documentation
